#!/bin/bash
user=`whoami`
character=$0
echo $character
the_character="${character##*/}"

sudo /usr/local/bin/.hogwarts/user_info.sh $user
level=$(sudo /usr/local/bin/.hogwarts/user_info.sh $user)
echo level $level

default(){
    cat /usr/local/src/hogwarts1/default/${the_character}.txt
}

if [ "$level" = "demo" ]
then 
    echo "DEMO!!!!"
    cat /usr/local/src/hogwarts1/demo/${the_character}.txt
elif [ "$level" = "year_one 0" ]
then 
    echo "YEAR ONE 0!!!!!"
    cat /usr/local/src/hogwarts1/level_0/${the_character}.txt
elif [ "$level" = "year_one 1" ]
then 
    echo "YEAR ONE 1!!!!!"
    cat /usr/local/src/hogwarts1/level_1/${the_character}.txt
elif [ "$level" = "year_one 2" ]
then 
    echo "YEAR ONE 2!!!!!"
    cat /usr/local/src/hogwarts1/level_2/${the_character}.txt
elif [ "$level" = "year_one 3" ]
then 
    echo "YEAR ONE 3!!!!!"
    cat /usr/local/src/hogwarts1/level_3/${the_character}.txt
elif [ "$level" = "year_one 4" ]
then 
    echo "YEAR ONE 4!!!!!"
    cat /usr/local/src/hogwarts1/level_4/${the_character}.txt
elif [ "$level" = "year_one 5" ]
then 
    echo "YEAR ONE 5!!!!!"
    cat /usr/local/src/hogwarts1/level_5/${the_character}.txt
elif [ "$level" = "year_one 6" ]
then 
    echo "YEAR ONE 6!!!!!"
    cat /usr/local/src/hogwarts1/level_6/${the_character}.txt
elif [ "$level" = "year_one 7" ]
then 
    echo "YEAR ONE 7!!!!!"
    cat /usr/local/src/hogwarts1/level_7/${the_character}.txt
elif [ "$level" = "year_one 8" ]
then 
    echo "YEAR ONE 8!!!!!"
    cat /usr/local/src/hogwarts1/level_8/${the_character}.txt
elif [ "$level" = "year_one 9" ]
then 
    echo "YEAR ONE 9!!!!!"
    cat /usr/local/src/hogwarts1/level_9/${the_character}.txt
elif [ "$level" = "year_one 10" ]
then 
    echo "YEAR ONE 10!!!!!"
    cat /usr/local/src/hogwarts1/level_10/${the_character}.txt
else
    echo "yikes, fell off a cliff"
    default
fi
#if [ "$level" = "demo" ]
#    then  
