#!/bin/bash
user=`whoami`
character=$0
# echo $character
the_character="${character##*/}"

# sudo /usr/local/bin/.hogwarts/user_info.sh $user
level=$(sudo /usr/local/bin/.hogwarts/user_info.sh $user)
# echo level $level

default(){
    cat /usr/local/src/hogwarts1/default/${the_character}.txt
}

if [ "$level" = "demo" ]
then 
    echo -e "$(cat /usr/local/src/hogwarts1/demo/${the_character}.txt)"
else 
    for i in {0..10}
    do
        if [ "$level" = "year_one 9" ]
        then
            if [ "$the_character" == "McGonagall" ] || [ "$the_character" == "Flitwick" ] || [ "$the_character" == "Quirell" ]
            then
                bash /usr/local/src/hogwarts1/level_9/${the_character}.txt 
            else
                echo -e "$(cat /usr/local/src/hogwarts1/level_9/${the_character}.txt)"
            fi
        elif [ "$level" = "year_one $i" ]
        then 
            echo -e "$(cat /usr/local/src/hogwarts1/level_$i/${the_character}.txt)"
        fi
    done
fi

