#!/bin/bash

user=`whoami`
character=$0
the_character="${character##*/}"

level=$(sudo /usr/local/bin/.hogwarts/user_info.sh $user)

default(){
    cat /usr/local/src/hogwarts1/default/${the_character}.txt
}

if [ "$level" = "demo" ]
then
    echo -e "$(cat /usr/local/src/hogwarts1/demo/Dumbledore.txt)"
    echo ""
    echo "Congratulations, you have successfully navigated around the castle!"
    echo "Do you wish to join Hogwarts"
    read -p "(yes/no) " join

    if [ $join = "yes" ]
    then
        sudo /usr/local/bin/.hogwarts/join.sh
        # echo $$
        the_pid=$(ps -o ppid= "$$")
        # echo $the_pid
        sudo /usr/local/bin/.hogwarts/boot_demo.sh $the_pid
    else
        echo "Oh well... maybe another day"
        echo -e "type \e[96mexit\e[0m in the command prompt to exit"
    fi
elif [ "$level" = "year_one 0" ]
then
    echo -e "$(cat /usr/local/src/hogwarts1/level_0/Dumbledore.txt)"
    # echo "Do you want to go to the next week's lessons?"
    read -p "(yes/no) " join
    if [ $join = "yes" ]
    then
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 1 
        # Welcome
    else
        echo "very well, come back when you are ready"
    fi
elif [ "$level" = "year_one 1" ]
then
    if [ "$(cat $location/hogwarts_castle/gryffindor_tower/dorms/$user/my_name.txt 2>&1)" == "$user" ]
    then
        echo "Congratulations! You have finished your homework!"
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 2 
        Welcome
    else
        echo -e "$(cat /usr/local/src/hogwarts1/level_1/Dumbledore.txt)"
    fi
elif [ "$level" = "year_one 2" ]
then
    if [ "$(cat $location/hogwarts_castle/gryffindor_tower/dorms/$user/closet/my_name.txt 2>&1)" == "$user" ]
    then
        echo "Congratulations! You have finished your homework!"
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 3 
        Welcome
    else
        echo -e "$(cat /usr/local/src/hogwarts1/level_2/Dumbledore.txt)"
    fi
elif [ "$level" = "year_one 3" ]
then
    echo -e "$(cat /usr/local/src/hogwarts1/level_3/Dumbledore.txt)"
    echo "Are you ready for your Christmas break?"
    read -p "(yes/no) " join
    if [ $join = "yes" ]
    then
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 4 
        cp /usr/local/bin/hogwarts/empty $location/hogwarts_castle/gryffindor_tower/dorms/$user/invisibility_cloak
        cp /usr/local/bin/hogwarts/empty $location/hogwarts_castle/gryffindor_tower/dorms/$user/flute
        Welcome
    else
        echo "very well, come back when you are ready"
    fi
elif [ "$level" = "year_one 4" ]
then
    echo -e "$(cat /usr/local/src/hogwarts1/level_4/Dumbledore.txt)"
    echo "Have you finished exploring?"
    read -p "(yes/no) " join
    if [ $join = "yes" ]
    then
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 5 
        Welcome
    else
        echo "very well, come back when you are ready"
    fi

elif [ "$level" = "year_one 5" ]
then
 
    if [ "$(cat $location/hogwarts_castle/gryffindor_tower/dorms/$user/permissions.txt 2>&1)" == "user group other" ]
    then
        echo "Yay! You finished your homework"   
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 6 
        Welcome
    else
        echo -e "$(cat /usr/local/src/hogwarts1/level_5/Dumbledore.txt)"
    fi   
    # echo "YEAR ONE 5!!!!!"
    # sudo /usr/local/bin/.hogwarts/power_up.sh $user 6 
elif [ "$level" = "year_one 6" ]
then
    
    if [ "$(ls -l $location/hogwarts_castle/gryffindor_tower/dorms/$user/my_permissions.txt | awk '{print $4}')" == "first_year" ]
    then
        echo "Yay! You finished your homework"
        sudo /usr/local/bin/.hogwarts/power_up.sh $user 7 
    else
        echo "Your homework was to create a file called my_permissions.txt in your dorm with the group set to year_one"
    fi
elif [ "$level" = "year_one 7" ]
then
    echo "YEAR ONE 7!!!!!"
    sudo /usr/local/bin/.hogwarts/power_up.sh $user 8 
elif [ "$level" = "year_one 8" ]
then
    echo "YEAR ONE 8!!!!!"
    sudo /usr/local/bin/.hogwarts/power_up.sh $user 9 
elif [ "$level" = "year_one 9" ]
then
    echo "YEAR ONE 9!!!!! You've reached the end... but one last thing"
elif [ "$level" = "year_one 10" ]
then
    echo "YEAR ONE 10!!!!! Yay! you've defeated the bad guy"
else
    echo "yikes, fell off a cliff"
    default
fi

