#!/bin/bash

echo -e "\e[31mWoah-ho-ho!\e[0m
\e[91mHello there, young mageling.\e[0m
\e[33mAren't you a little explorer?\e[0m
\e[92mYou've hit the root or \"/\" of Hogwarts Tech.\e[0m
\e[32mFeel free to take a look around.\e[0m
\e[36mRoots may not make sense now, but you'll learn more about them in the future.\e[0m
\e[35mBut only if you keep taking those classes!\e[0m
"
