#!/bin/bash
user=`whoami`
character=$0
#jjecho $character
the_character="${character##*/}"

#sudo /usr/local/bin/.hogwarts/user_info.sh $user
level=$(sudo /usr/local/bin/.hogwarts/user_info.sh $user)
#echo level $level

default(){
    cat /usr/local/src/hogwarts1/default/Welcome.txt
}

if [ "$level" = "demo" ]
then 
    for j in {1..10}
    do 
        echo ""
    done
    echo -e "$(cat /usr/local/src/hogwarts1/demo/Welcome.txt)"
else
    for i in {0..10}
    do
        if [ "$level" = "year_one $i" ]
        then
            for j in {1..10}
            do
                echo ""
            done
            echo -e "$(cat /usr/local/src/hogwarts1/level_$i/Welcome.txt)"    
        fi
    done
fi

